---
- name: copy site configuration
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-available/{{ app }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart nginx

- name: symlink site configuration
  file:
    src: "/etc/nginx/sites-available/{{ app }}"
    dest: "/etc/nginx/sites-enabled/{{ app }}"
    owner: root
    group: root
    mode: 0644
    state: link
  notify:
    - restart nginx

- name: ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
