---
- name: add user
  user:
    name: "{{ user }}"
    state: present
    home: "/home/{{ user }}"
    shell: /bin/bash

- name: copy authorized_keys for user
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    path: "/home/{{ user }}/.ssh/authorized_keys"
    state: present
    manage_dir: no

- name: change ownership of ssh directory
  file:
    path: "/home/{{ user }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: user